import type { Email, Note } from '../types'

export function summarizeEmail(email: Email, notes: Note[]): string {
  const linked = email.linkedNoteId
    ? notes.find((n) => n.id === email.linkedNoteId)
    : null

  const lines: string[] = []
  lines.push(`**From:** ${email.fromName}`)
  lines.push(`**Subject:** ${email.subject}`)
  lines.push('')
  lines.push('**Summary**')

  const body = email.body.toLowerCase()
  if (body.includes('update') || body.includes('project')) {
    lines.push(`Project-related update from ${email.fromName}. Key action items and timeline references are included.`)
  } else if (body.includes('reminder') || body.includes('submit')) {
    lines.push(`Reminder email with a deadline. Requires follow-up action from you.`)
  } else if (body.includes('meeting') || body.includes('invitation')) {
    lines.push(`Calendar-related message about an upcoming meeting or event.`)
  } else {
    lines.push(email.preview)
  }

  const bullets: string[] = []
  if (body.includes('feedback')) bullets.push('Feedback requested')
  if (body.includes('review')) bullets.push('Review or approval needed')
  if (body.includes('deadline') || body.includes('june 30')) bullets.push('Deadline mentioned')
  if (body.includes('budget')) bullets.push('Budget-related content')
  if (body.includes('sync') || body.includes('meeting')) bullets.push('Meeting coordination')

  if (bullets.length > 0) {
    lines.push('')
    lines.push('**Key points**')
    bullets.forEach((b) => lines.push(`- ${b}`))
  }

  if (linked) {
    lines.push('')
    lines.push(`**Linked vault note:** [[${linked.title}]]`)
    lines.push(`This email is connected to your ${linked.title} note in the knowledge graph.`)
  }

  lines.push('')
  lines.push('*Generated by EtherMail Vault AI*')

  return lines.join('\n')
}
